# Generated by Django 4.2.5 on 2024-01-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='changed_at',
            field=models.DateTimeField(verbose_name='Изменено'),
        ),
    ]
