# Generated by Django 5.0 on 2024-01-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=None, verbose_name='Создано'),
            preserve_default=False,
        ),
    ]
